/// Flutter icons Custom_Icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_Icons
///      fonts:
///       - asset: fonts/Custom_Icons.ttf
///
///
///
import 'package:flutter/widgets.dart';

// ignore: camel_case_types
class Custom_Icons {
  Custom_Icons._();

  static const _kFontFam = 'Custom_Icons';
  static const _kFontPkg = null;

  static const IconData creative_studio_24px =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_change_24px =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData premium =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData incognito_mode_24px =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personal_data_24px =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mynorthwest_24px =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptions_24px =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
